# **Problem Statement**  
## **29. Implement a basic ANN (Artificial Neural Network) using Keras/TensorFlow.**

Implement a basic Artificial Neural Network (ANN) using Keras/TensorFlow to perform binary classification on a dataset.

The model should:
- Use fully connected (Dense) layers
- Be trained using backpropagation
- Be evaluated using accuracy

### Constraints & Example Inputs/Outputs

### Constraints
- Numerical input features
- Binary output (0 or 1)
- Small dataset for demonstration
- Activation functions: ReLU, Sigmoid

### Example Input:
```python
X = [[0.1, 0.2],
     [0.2, 0.8],
     [0.8, 0.2],
     [0.9, 0.7]]

y = [0, 0, 1, 1]

```

Expected Output:
```python
Training Accuracy: ~95%
Predictions: [0, 0, 1, 1]

```

### Solution Approach

**Step 1: Prepare Dataset**
- Split features (X) and labels (y)
- Normalize input values if needed

**Step 2: Build ANN Architecture**
- Input layer
- One or more hidden layers (ReLU)
- Output layer (Sigmoid for binary classification)

**Step 3: Compile the Model**
- Loss function: Binary Crossentropy
- Optimizer: Adam
- Metric: Accuracy

**Step 4: Train the Model**
- Use backpropagation
- Adjust weights via gradient descent

**Step 5: Evaluate & Predict**
- Check accuracy
- Generate predictions
- Validate correctness

### Solution Code

In [2]:
!pip3 install tensorflow

  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
  Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 620.7/620.7 MB 16.8 MB/s  0:00:31 eta 0:00:010:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 19.1 MB/s  0:00:00 22.6 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 19.7 MB/s  0:00:003.3 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 18.3 MB/s  0:00:002.3 MB/s eta 0:00:01
Using cached flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 18.2 MB/s  0:00:00 22.6 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 16.2 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 19.4 MB/s  0:00:01 eta 0:00:010:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20/20 [tensorflow]0m 19/20 [tensorflow]]


In [3]:
# Import Required Libraries
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam


2026-01-05 19:45:36.566627: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-05 19:45:36.597725: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-01-05 19:45:37.539427: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
/home/piai/jupyter_env/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: Futu

In [4]:
# Approach 1: Brute Force ANN (Conceptual – Single Neuron)
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def single_neuron_predict(X, weights, bias):
    return sigmoid(np.dot(X, weights) + bias)


In [5]:
# Example Run
X_sample = np.array([[0.8, 0.6]])
weights = np.array([1.2, -0.8])
bias = 0.1

output = single_neuron_predict(X_sample, weights, bias)
output


array([0.64106741])

### Alternative Solution

In [6]:
# Approach 2: Optimized ANN Using Keras
# Create the Dataset
X = np.array([
    [0.1, 0.2],
    [0.2, 0.8],
    [0.8, 0.2],
    [0.9, 0.7]
])

y = np.array([0, 0, 1, 1])

#Build ANN Model
model = Sequential([
    Dense(8, activation='relu', input_shape=(2,)),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])

#Compile Model
model.compile(
    optimizer=Adam(learning_rate=0.01),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

#Train Model
history = model.fit(
    X, y,
    epochs=100,
    batch_size=2,
    verbose=0
)

#Evaluate Model
loss, accuracy = model.evaluate(X, y, verbose=0)
accuracy

#Predictions
pred_probs = model.predict(X)
pred_labels = (pred_probs > 0.5).astype(int)

pred_labels.flatten()


/home/piai/jupyter_env/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
W0000 00:00:1767622727.916318  243960 gpu_device.cc:2342] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([0, 0, 1, 1])

### Alternative Approaches

**Brute Force Alternatives**
- Single-layer perceptron
- Manual gradient descent (only for learning purpose, not good for production)

**Optimized / Advanced**
- Deeper networks
- Dropout
- Batch Normalization
- PyTorch implementation

### Test Case

In [7]:
# Test Case 1: Accuracy Threshhold
assert accuracy > 0.9
print("Test Case 1 Passed: High Accuracy")


Test Case 1 Passed: High Accuracy


In [8]:
# Test Case 2: Prediction Shape
assert pred_labels.shape == (4, 1)
print("Test Case 2 Passed: Prediction Shape OK")


Test Case 2 Passed: Prediction Shape OK


In [9]:
# TTest Case 3: Correct Classification
expected = np.array([0, 0, 1, 1])
assert np.array_equal(pred_labels.flatten(), expected)
print("Test Case 3 Passed: Correct Predictions")


Test Case 3 Passed: Correct Predictions


In [10]:
# Test Case 4: New Sample Prediction
new_sample = np.array([[0.85, 0.65]])
new_pred = model.predict(new_sample)
new_pred > 0.5


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[ True]])

## Complexity Analysis

### ANN (Per Epoch)
- Time: O(n × d × h)
- Space: O(d × h)

Where:
- n = samples
- d = input features
- h = hidden units

#### Thank You!!