# **Problem Statement**  
## **7. Perform min-max normalization and z-score normalization manually.**

Given a numerical dataset, manually perform:

1. Min-Max Normalization
2. Z-Score Normalization (Standardization)

Do not use any preprocessing utilities from libraries like sklearn.
The goal is to understand and implement normalization mathematically.

### Constraints & Example Inputs/Outputs

- Input is a list or NumPy array of numerical values
- Dataset must contain at least one element
- Handle edge cases (zero variance)

#### Example Input:
```python
data = [10, 20, 30, 40, 50]

```

#### Expected Output:

Min-Max Normalization (0-1)
```python
[0.0, 0.25, 0.5, 0.75, 1.0]
```

#### Z-Score Normalization
```python
[-1.41, -0.71, 0.0, 0.71, 1.41]
```

### Solution Approach

### Min-Max Normalization
Scales data to a fixed range (usually 0–1).

### Z-Score Normalization
Centers data around mean with unit variance.

### Approach
- Compute min, max, mean, std manually
- Apply normalization formula element-wise
- Handle division-by-zero cases

### Solution Code

In [2]:
# Approach 1: Brute Force Min-Max Normalization
def min_max_normalization_bruteforce(data):
    minimum = min(data)
    maximum = max(data)
    
    normalized = []
    for x in data:
        if maximum - minimum == 0:
            normalized.append(0)
        else:
            normalized.append((x - minimum) / (maximum - minimum))
    
    return normalized


In [3]:
# Approach 2: Brute Force Z-Score Normalization
import math

def z_score_normalization_bruteforce(data):
    n = len(data)
    mean = sum(data) / n
    
    variance = sum((x - mean) ** 2 for x in data) / n
    std_dev = math.sqrt(variance)
    
    normalized = []
    for x in data:
        if std_dev == 0:
            normalized.append(0)
        else:
            normalized.append((x - mean) / std_dev)
    
    return normalized



### Alternative Solution

In [4]:
# Approach 2: Optimized Version Using NumPy (Still Manual Logic)
import numpy as np

def min_max_normalization_optimized(data):
    data = np.array(data)
    min_val = np.min(data)
    max_val = np.max(data)
    
    if max_val - min_val == 0:
        return np.zeros(len(data))
    
    return (data - min_val) / (max_val - min_val)


def z_score_normalization_optimized(data):
    data = np.array(data)
    mean = np.mean(data)
    std = np.std(data)
    
    if std == 0:
        return np.zeros(len(data))
    
    return (data - mean) / std


### Alternative Approaches

- Log normalization
- Robust scaling (median & IQR)
- Unit vector normalization
- sklearn.preprocessing (not allowed here)

### Test Case

In [5]:
# Test Case 1: Simple Increasing Data
data = [10, 20, 30, 40, 50]

print("Min-Max (Brute):", min_max_normalization_bruteforce(data))
print("Z-Score (Brute):", z_score_normalization_bruteforce(data))

print("Min-Max (Optimized):", min_max_normalization_optimized(data))
print("Z-Score (Optimized):", z_score_normalization_optimized(data))


Min-Max (Brute): [0.0, 0.25, 0.5, 0.75, 1.0]
Z-Score (Brute): [-1.414213562373095, -0.7071067811865475, 0.0, 0.7071067811865475, 1.414213562373095]
Min-Max (Optimized): [0.   0.25 0.5  0.75 1.  ]
Z-Score (Optimized): [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [6]:
# Test Case 2: Data with Negative Values
data = [-10, 0, 10, 20]

print(min_max_normalization_optimized(data))
print(z_score_normalization_optimized(data))


[0.         0.33333333 0.66666667 1.        ]
[-1.34164079 -0.4472136   0.4472136   1.34164079]


In [7]:
# Test Case 3: Constant Values (Edge Case)
data = [5, 5, 5, 5]

print(min_max_normalization_optimized(data))
print(z_score_normalization_optimized(data))


[0. 0. 0. 0.]
[0. 0. 0. 0.]


In [8]:
# Test Case 4: Real-World Style Data
data = [56, 65, 72, 80, 90]

print("Min-Max:", min_max_normalization_optimized(data))
print("Z-Score:", z_score_normalization_optimized(data))


Min-Max: [0.         0.26470588 0.47058824 0.70588235 1.        ]
Z-Score: [-1.41185867 -0.64639313 -0.05103104  0.62938278  1.47990005]


## Complexity Analysis

### Time Complexity
- Min-Max: O(n)
- Z-Score: O(n)

### Space Complexity
O(n) for storing normalized values

#### Thank You!!